In [2]:
import import_ipynb
import numpy as np
import pandas as pd
import random
from __future__ import division, print_function
import math

In [8]:
df = pd.read_csv("vote/vote.data", delimiter='\t', header=None) 
df.head()

  0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
0  n  y  n  y  y  y  n  n  n  y  ?  y  y  y  n  y  r
1  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?  r
2  ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n  d
3  n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y  d
4  y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y  d

In [ ]:
()