In [1]:
import numpy as np
import pandas as pd
import random

%matplotlib inline

In [2]:
df = pd.read_csv("WineData/wine.txt", header=None)

In [3]:
train = pd.read_csv("WineData/train_wine.csv", header=None) 
test = pd.read_csv("WineData/test_wine.csv", header=None) 
test.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.56,1.73,2.46,20.5,116,2.96,2.78,0.20,2.45,6.25,0.98,3.03,1120
2,3,12.79,2.67,2.48,22.0,112,1.48,1.36,0.24,1.26,10.80,0.48,1.47,480
3,2,12.17,1.45,2.53,19.0,104,1.89,1.75,0.45,1.03,2.95,1.45,2.23,355
4,1,14.22,1.70,2.30,16.3,118,3.20,3.00,0.26,2.03,6.38,0.94,3.31,970

In [4]:
df = train.append(test)
df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
23,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
24,2,12.42,2.55,2.27,22.0,90,1.68,1.84,0.66,1.42,2.70,0.86,3.30,315
25,2,12.64,1.36,2.02,16.8,100,2.02,1.41,0.53,0.62,5.75,0.98,1.59,450
26,2,11.76,2.68,2.92,20.0,103,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607
27,2,11.79,2.13,2.78,28.5,92,2.13,2.24,0.58,1.76,3.00,0.97,2.44,466

In [5]:
df_norm = df[[1,2,3,4,5,6,7,8,9,10,11,12,13]].apply(lambda x: (x - x.min()) / (x.max() - x.min()))
df_norm.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.283019,0.593060,0.372014,0.455285,0.970696,0.561341
1,0.163158,0.183794,0.673797,0.793814,0.195652,0.324138,0.267932,0.509434,0.293375,0.112628,0.715447,0.710623,0.202568
2,0.100000,0.000000,0.609626,0.536082,0.195652,0.517241,0.352321,0.547170,0.324921,0.153584,0.504065,0.380952,0.111270
3,0.723684,0.399209,0.502674,0.587629,0.217391,0.127586,0.071730,0.528302,0.195584,0.708191,0.178862,0.150183,0.240371
4,0.597368,0.193676,0.417112,0.329897,0.260870,0.489655,0.390295,0.264151,0.296530,0.227816,0.439024,0.549451,0.718260

In [6]:
target = df[[0]]
df = pd.concat([df_norm, target], axis=1)
df.columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'label']
label_cols = pd.get_dummies(df.label)
df = pd.concat([df_norm, label_cols], axis=1)
df.columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'label1', 'label2', 'label3']
df.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,label1,label2,label3
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.283019,0.593060,0.372014,0.455285,0.970696,0.561341,1,0,0
1,0.163158,0.183794,0.673797,0.793814,0.195652,0.324138,0.267932,0.509434,0.293375,0.112628,0.715447,0.710623,0.202568,0,1,0
2,0.100000,0.000000,0.609626,0.536082,0.195652,0.517241,0.352321,0.547170,0.324921,0.153584,0.504065,0.380952,0.111270,0,1,0
3,0.723684,0.399209,0.502674,0.587629,0.217391,0.127586,0.071730,0.528302,0.195584,0.708191,0.178862,0.150183,0.240371,0,0,1
4,0.597368,0.193676,0.417112,0.329897,0.260870,0.489655,0.390295,0.264151,0.296530,0.227816,0.439024,0.549451,0.718260,1,0,0

In [7]:
train = df.iloc[:151, :]
train.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,label1,label2,label3
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.283019,0.593060,0.372014,0.455285,0.970696,0.561341,1,0,0
1,0.163158,0.183794,0.673797,0.793814,0.195652,0.324138,0.267932,0.509434,0.293375,0.112628,0.715447,0.710623,0.202568,0,1,0
2,0.100000,0.000000,0.609626,0.536082,0.195652,0.517241,0.352321,0.547170,0.324921,0.153584,0.504065,0.380952,0.111270,0,1,0
3,0.723684,0.399209,0.502674,0.587629,0.217391,0.127586,0.071730,0.528302,0.195584,0.708191,0.178862,0.150183,0.240371,0,0,1
4,0.597368,0.193676,0.417112,0.329897,0.260870,0.489655,0.390295,0.264151,0.296530,0.227816,0.439024,0.549451,0.718260,1,0,0

In [8]:
test = df.iloc[151: , :]
test.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,label1,label2,label3
0,0.842105,0.191700,0.572193,0.257732,0.619565,0.627586,0.573840,0.283019,0.593060,0.372014,0.455285,0.970696,0.561341,1,0,0
1,0.665789,0.195652,0.588235,0.510309,0.500000,0.682759,0.514768,0.132075,0.643533,0.424061,0.406504,0.644689,0.600571,1,0,0
2,0.463158,0.381423,0.598930,0.587629,0.456522,0.172414,0.215190,0.207547,0.268139,0.812287,0.000000,0.073260,0.144080,0,0,1
3,0.300000,0.140316,0.625668,0.432990,0.369565,0.313793,0.297468,0.603774,0.195584,0.142491,0.788618,0.351648,0.054922,0,1,0
4,0.839474,0.189723,0.502674,0.293814,0.521739,0.765517,0.561181,0.245283,0.511041,0.435154,0.373984,0.747253,0.493581,1,0,0

In [9]:
def sigmoid(z):
    return 1/(1 + np.exp(-(z)))

In [10]:
def softmax(z):
    e = np.exp(z - np.sum(z, axis=1, keepdims=True))
    return e / np.sum(e, axis=1, keepdims=True)

In [11]:
def cross_entropy(y, y_pred):
    m = y.shape[0]
    cost = -(1.0/m) * np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))
    return cost

In [12]:
X = train.values[:,:13]
X[:5]

array([[0.84210526, 0.1916996 , 0.57219251, 0.25773196, 0.61956522,
        0.62758621, 0.57383966, 0.28301887, 0.59305994, 0.37201365,
        0.45528455, 0.97069597, 0.56134094],
       [0.16315789, 0.18379447, 0.67379679, 0.79381443, 0.19565217,
        0.32413793, 0.26793249, 0.50943396, 0.29337539, 0.11262799,
        0.71544715, 0.71062271, 0.20256776],
       [0.1       , 0.        , 0.60962567, 0.53608247, 0.19565217,
        0.51724138, 0.35232068, 0.54716981, 0.32492114, 0.15358362,
        0.50406504, 0.38095238, 0.11126961],
       [0.72368421, 0.39920949, 0.5026738 , 0.58762887, 0.2173913 ,
        0.12758621, 0.07172996, 0.52830189, 0.1955836 , 0.70819113,
        0.17886179, 0.15018315, 0.2403709 ],
       [0.59736842, 0.19367589, 0.4171123 , 0.32989691, 0.26086957,
        0.48965517, 0.39029536, 0.26415094, 0.29652997, 0.2278157 ,
        0.43902439, 0.54945055, 0.71825963]])

In [13]:
num_inputs = len(X[0])
hidden_layer_neurons = 5
np.random.seed(4)
w1 = np.random.random((num_inputs, hidden_layer_neurons)) - 1
w1

array([[-0.03297016, -0.45276775, -0.02731564, -0.28518401, -0.30227118],
       [-0.7839105 , -0.02372555, -0.99376974, -0.74701764, -0.56520847],
       [-0.22061708, -0.80231493, -0.13700676, -0.01659932, -0.83615776],
       [-0.40266606, -0.9910139 , -0.61342872, -0.95583994, -0.04334703],
       [-0.56385335, -0.05102269, -0.21369401, -0.1337107 , -0.82683458],
       [-0.92505141, -0.39925728, -0.83202782, -0.26661983, -0.59155614],
       [-0.47209118, -0.06242842, -0.47830388, -0.89180662, -0.84177659],
       [-0.45479735, -0.47559592, -0.36238976, -0.59850456, -0.35019489],
       [-0.6031    , -0.37608389, -0.23259503, -0.82102609, -0.62442423],
       [-0.49746694, -0.31333292, -0.74632035, -0.44525914, -0.37506916],
       [-0.10449883, -0.63714641, -0.36244293, -0.8085536 , -0.50220589],
       [-0.8175546 , -0.08161696, -0.56817793, -0.1698119 , -0.5832237 ],
       [-0.09533241, -0.59517478, -0.6688255 , -0.42786123, -0.15455635]])

In [14]:
y = np.array(train.iloc[:, 13:])
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=uint8)

In [15]:
num_outputs = len(y[0])
w2 = np.random.random((hidden_layer_neurons, num_outputs)) - 1
w2

array([[-0.13898569, -0.40431188, -0.91533839],
       [-0.40273339, -0.75454629, -0.26740655],
       [-0.10534871, -0.48526603, -0.39643649],
       [-0.93493219, -0.45992527, -0.87081322],
       [-0.38543715, -0.63634965, -0.23224197]])

In [16]:
learning_rate = 0.2 
for epoch in range(50000):
    z1 = np.dot(X, w1)
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2)
    a2 = softmax(z2)
    loss = cross_entropy(y, a2)
    a2_delta = (y - a2)*(a2 * (1-a2))
    a1_delta = a2_delta.dot(w2.T) * (a1 * (1-a1))
    w2 += a1.T.dot(a2_delta) * learning_rate
    w1 += X.T.dot(a1_delta) * learning_rate
print('Loss:', loss)

Error: 0.0018236947691951135

In [17]:
z1 = np.dot(X, w1)
a1 = sigmoid(z1)
z2 = np.dot(a1, w2)
a2 = softmax(z2)

np.round(a2,3)

array([[1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.002, 0.998],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.988, 0.012, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.007, 0.993, 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.001, 0.999],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [0.002, 0.998, 0.   ],
       [0.   , 0.002, 0.998],
       [0.   , 0.001, 0.999],
       [1.   , 0.   , 0.   ],
       [0.005, 0.995, 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.004, 0.995, 0.001],
       [0.   , 1.   , 0.   ],
       [0.996, 0.004, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.004, 0.996, 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.007, 0.993, 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.005, 0.99 , 0.004],
       [0.999, 0.001, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.997, 0.003, 0.   ],
       [0.   , 0.   , 1.   ],
       [0.995, 0.005, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.997, 0.003, 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.003, 0.997],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.001, 0.999, 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.998, 0.002, 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.008, 0.992],
       [1.   , 0.   , 0.   ],
       [0.   , 0.005, 0.995],
       [0.   , 1.   , 0.   ],
       [0.998, 0.002, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.993, 0.007, 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.006, 0.994],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.995, 0.005],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [0.999, 0.001, 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.004, 0.991, 0.005],
       [0.003, 0.991, 0.005],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ]])

In [18]:
y_pred = np.argmax(a2, axis=1)
y_result = np.argmax(y, axis = 1)
result = y_pred == np.argmax(y, axis=1)
correct = np.sum(result)/len(result)

print('Correct:',sum(result),'/',len(result))
print('Accuracy:', (correct*100),'%')

Correct: 151 / 151
Accuracy: 100.0 %

In [19]:
X = test.values[:,:13]
y = np.array(test.iloc[:, 13:])

z1 = np.dot(X, w1)
a1 = sigmoid(z1)
z2 = np.dot(a1, w2)
a2 = softmax(z2)

np.round(a2,3)

array([[1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.   , 0.   , 1.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ],
       [0.004, 0.996, 0.   ],
       [1.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   ],
       [0.012, 0.988, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.995, 0.005, 0.   ],
       [1.   , 0.   , 0.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.986, 0.014],
       [0.002, 0.998, 0.   ],
       [0.   , 1.   , 0.   ]])

In [20]:
y_pred = np.argmax(a2, axis=1)
y_result = np.argmax(y, axis = 1)
result = y_pred == np.argmax(y, axis=1)
correct = np.sum(result)/len(result)

print('Correct:',sum(result),'/',len(result))
print( 'Accuracy:', (correct*100),'%')

Correct: 28 / 28
Accuracy: 100.0 %

In [21]:
y_pred

array([0, 0, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1])