In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import pinv
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import random
from pprint import pprint

In [2]:
word_labels = ["CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "label"]
train_df = pd.read_csv("HousingData/housing_train.txt", delim_whitespace=True, names = word_labels, header=None) 
test_df = pd.read_csv("HousingData/housing_test.txt", delim_whitespace=True, names = word_labels, header=None)

In [3]:
train_df.insert(0, 'Ones', 1)
col_nums = train_df.shape[1]

X = train_df.iloc[:,0:col_nums-1]  
y = train_df.iloc[:,col_nums-1:col_nums] 
y

     label
0     24.0
1     21.6
2     34.7
3     33.4
4     36.2
5     28.7
6     22.9
7     27.1
8     16.5
9     18.9
10    15.0
11    18.9
12    21.7
13    20.4
14    18.2
15    19.9
16    23.1
17    17.5
18    20.2
19    18.2
20    13.6
21    19.6
22    15.2
23    14.5
24    15.6
25    12.7
26    14.5
27    13.2
28    13.1
29    13.5
..     ...
403   19.6
404   23.2
405   29.8
406   13.8
407   13.3
408   16.7
409   12.0
410   14.6
411   21.4
412   23.0
413   23.7
414   25.0
415   21.8
416   20.6
417   21.2
418   19.1
419   20.6
420   21.8
421   24.5
422   23.1
423   19.7
424   18.3
425   21.2
426   17.5
427   16.8
428   22.4
429   20.6
430   23.9
431   22.0
432   11.9

[433 rows x 1 columns]

In [4]:
IdentitySize = X.shape[1]
IdentityMatrix= np.zeros((IdentitySize, IdentitySize))
np.fill_diagonal(IdentityMatrix, 1)

In [5]:
a_cont = 1
xTx = X.T.dot(X) + a_cont * IdentityMatrix
XtX = np.linalg.pinv(xTx)
XtX_xT = XtX.dot(X.T)
coefficient = XtX_xT.dot(y)

In [6]:
coefficient

array([[ 1.48622145e+01],
       [-9.85658172e-02],
       [ 4.86195726e-02],
       [-2.94971257e-02],
       [ 3.16026913e+00],
       [-4.12425073e+00],
       [ 4.90156039e+00],
       [-1.46512415e-03],
       [-1.21594914e+00],
       [ 2.91613389e-01],
       [-1.45004225e-02],
       [-6.24613946e-01],
       [ 1.41627179e-02],
       [-5.35756523e-01]])

In [7]:
y_pred_train = coefficient.T.dot(X.T)

In [8]:
y_pred_train = y_pred_train.T 
mse = np.mean((y - y_pred_train)**2)
mse

label    23.042266
dtype: float64

In [9]:
test_df.insert(0, 'Ones', 1)
col_nums = test_df.shape[1]
X = test_df.iloc[:,0:col_nums-1]  
y = test_df.iloc[:,col_nums-1:col_nums] 
y_pred = coefficient.T.dot(X.T)

y_pred

array([[13.27196364, 16.00545167, 15.08281134, 20.84224132, 22.29981213,
        17.10694219,  7.4021553 , 16.01201246, 21.29759191, 21.71232873,
        19.91471715, 20.67693144, 28.54130218, 25.3080471 , 26.44269471,
        18.55409824, 20.3178113 , 20.93788918, 16.04475956, 12.8036749 ,
        18.02014052, 16.09833719, 15.98493399,  8.84694885, 20.50476834,
        24.53469295, 25.07934534, 20.22000019, 30.84482092, 33.67214272,
        30.10691242, 29.4463197 , 32.5890937 , 33.5330476 , 23.19499193,
        32.5343472 , 24.73695126, 24.52844209, 25.25253123, 26.1363266 ,
        32.63529367, 35.29349192, 35.54894662, 26.12816039, 19.88834732,
        26.00261362, 15.5321175 , 18.10042917, 21.79740953, 25.25660766,
        24.57331729, 20.99105204, -1.49361701, 26.87413232, 18.76722127,
        12.52409445, 14.95892104, -2.62150581,  9.18421424, 13.47388835,
        13.04635088, 13.25386883, 11.8142393 , 18.77370776, 19.54248706,
        17.63388025, 12.66097713, 15.6744817 , 16.04050923, 12.57745057,
        14.93023612, 20.41885493, 20.65203017, 16.7209229 ]])

In [10]:
y_pred = y_pred.T 
mse = np.mean((y - y_pred)**2)
mse

label    22.828525
dtype: float64